### ISSUE TITLE
npm kml-geojson 的版本版本不一致

### ISSUE THREAD

**Issue by JohnsonMao** [muyao1987/kml-geojson#2]
目前 [npm kml-geojson](https://www.npmjs.com/package/kml-geojson) 的版本是 1.2.0
與您目前的 repository 的版本不一致
導致我安裝的會出現 `Cesium is not defined`
再麻煩更新～感謝！
![image](https://user-images.githubusercontent.com/86179381/236370610-8db012bf-562c-4090-af9a-cb859e537fe6.png)

**Comment by muyao1987** [comment]
谢谢反馈，目前已发布
